### ISSUE TITLE
能否在离线环境中使用？

### ISSUE THREAD

**Issue by houluy** [lzjun567/flask-siwadoc#23]
希望在公司内网使用，有些js脚本能否通过外网机器下载后配置到工程内，从而无Internet环境也能够打开文档页面？

**Comment by lzjun567** [comment]
可设置访问权限
配置参数：

SIWA_USER：登录用户名
SIWA_PASSWORD: 登录密码
只有同时设置了用户名和密码访问文档才需要登录权限，该场景用在正式环境中，防止接口文档被匿名访问

**Comment by houluy** [comment]
谢作者大大。主要是HTML模板文件里有一些css，js等必须联网，我把这些文件下载下来从Flask serve出去，就可以在内网使用siwa了。
